# Generated by Django 5.1.1 on 2024-10-02 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="is_published",
            field=models.BooleanField(default=True, verbose_name="признак публикации"),
        ),
        migrations.AddField(
            model_name="blog",
            name="slug",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="slug"
            ),
        ),
        migrations.AddField(
            model_name="blog",
            name="views_counter",
            field=models.IntegerField(default=0, verbose_name="количество просмотров"),
        ),
        migrations.AlterField(
            model_name="blog",
            name="created_at",
            field=models.DateField(auto_now=True),
        ),
    ]
