# Generated by Django 5.1.1 on 2024-10-02 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_blog_is_published_blog_slug_blog_views_counter_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="created_at",
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
